# Generated by Django 5.2.3 on 2025-12-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'waiting payment'), ('Processing', 'Processing'), ('Shipped', 'Sent to the post'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
